version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bovode-db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres:
    name: bovode-db